export const rocketComponents = {
  // TODO: add back once https://github.com/lit/lit/issues/2633 is fixed
  // 'rotating-text': '@rocket/components/rotating-text.js::RotatingText',
  'block-columns': '@rocket/components/block-columns.js::BlockColumns',
  'testimonial-small': '@rocket/components/testimonial-small.js::TestimonialSmall',
  'feature-small': '@rocket/components/feature-small.js::FeatureSmall',
  'the-block': '@rocket/components/the-block.js::TheBlock',
  'inline-notification': '@rocket/components/inline-notification.js::InlineNotification',
  'permanent-notification': '@rocket/components/permanent-notification.js::PermanentNotification',
  'card-icon': '@rocket/components/card-icon.js::CardIcon',
  'server-icon': '@rocket/components/server-icon.js::ServerIcon',
  'opengraph-overview': '@rocket/components/open-graph-overview.js::OpenGraphOverview',
  // 'rocket-dialog': '@rocket/components/dialog.js::RocketDialog',
  'rocket-drawer': '@rocket/components/drawer.js::RocketDrawer',
  'rocket-header': '@rocket/components/header.js::RocketHeader',
  'main-docs': '@rocket/components/main-docs.js::MainDocs',
  'main-content': '@rocket/components/main-content.js::MainContent',
  'rocket-social-link': '@rocket/components/social-link.js::RocketSocialLink',
  'content-area': '@rocket/components/content-area.js::ContentArea',
};
