export const rocketComponents = {
  'rocket-columns': '@rocket/components/columns.js::RocketColumns',
  'rocket-card': '@rocket/components/card.js::RocketCard',
  'rocket-content-area': '@rocket/components/content-area.js::RocketContentArea',
  'rocket-details': '@rocket/components/details.js::RocketDetails',
  // 'rocket-dialog': '@rocket/components/dialog.js::RocketDialog',
  'rocket-drawer': '@rocket/components/drawer.js::RocketDrawer',
  'rocket-feature-small': '@rocket/components/feature-small.js::RocketFeatureSmall',
  'rocket-header': '@rocket/components/header.js::RocketHeader',
  'rocket-header-scroll-menu': '@rocket/components/header-scroll-menu.js::RocketHeaderScrollMenu',
  'rocket-icon': '@rocket/components/icon.js::RocketIcon',
  'rocket-icon-card': '@rocket/components/icon-card.js::RocketIconCard',
  'rocket-main': '@rocket/components/main.js::RocketMain',
  'rocket-main-docs': '@rocket/components/main-docs.js::RocketMainDocs',
  'rocket-opengraph-overview': '@rocket/components/open-graph-overview.js::RocketOpenGraphOverview',
  'rocket-rotating-text': '@rocket/components/rotating-text.js::RocketRotatingText',
  'rocket-social-link': '@rocket/components/social-link.js::RocketSocialLink',
  'rocket-testimonial-small': '@rocket/components/testimonial-small.js::RocketTestimonialSmall',
  'inline-notification': '@rocket/components/inline-notification.js::InlineNotification',
  'permanent-notification': '@rocket/components/permanent-notification.js::PermanentNotification',
};
