import { unlink } from 'fs/promises';
import { existsSync } from 'fs';

/**
 * @param {string} sourceFilePath
 */
export async function cleanupAutoGeneratedFiles(sourceFilePath) {
  if (sourceFilePath.endsWith('.rocket.md')) {
    const mdInJsFilePath = sourceFilePath.replace('.rocket.md', '.rocketGeneratedMdInJs.js');
    const jsTemplateFilePath = sourceFilePath.replace('.rocket.md', '.rocketGeneratedFromMd.js');

    if (existsSync(mdInJsFilePath)) {
      await unlink(mdInJsFilePath);
    }
    if (existsSync(jsTemplateFilePath)) {
      await unlink(jsTemplateFilePath);
    }
  }
  if (sourceFilePath.endsWith('.rocket.html')) {
    const htmlTemplateFilePath = sourceFilePath.replace('.rocket.html', '-converted-html.js');
    if (existsSync(htmlTemplateFilePath)) {
      await unlink(htmlTemplateFilePath);
    }
  }
}
