name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    timeout-minutes: 15
    # Prevents deploy action from PRs via forks
    if: github.repository == 'modernweb-dev/rocket'
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Setup Node.js 22
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: package-lock.json

      # Set up GitHub Actions caching for Wireit.
      - uses: google/wireit@setup-github-actions-caching/v2

      - name: Install Dependencies
        run: npm ci

      - name: Publish to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: npm run deploy
