name: Verify changes

on: pull_request

jobs:
  verify-linux:
    name: Verify linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: google/wireit@setup-github-actions-caching/v1
      - uses: actions/checkout@v2

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright dependencies
        run: npx playwright install-deps

      - name: Install Playwright
        run: npx playwright install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test
